import argparse
import os
import re
from pathlib import Path
from PyPDF2 import PdfReader
from text_utils import reflow_paragraphs


def parse_translations(md_path):
    if not os.path.exists(md_path):
        return {}
    txt = open(md_path, "r", encoding="utf-8").read()
    parts = re.split(r"\n## Page (\d+)\n", txt)
    trans = {}
    for i in range(1, len(parts), 2):
        num = int(parts[i])
        body = parts[i + 1].strip()
        trans[num] = body
    return trans


def parse_plan(md_path):
    if not os.path.exists(md_path):
        return []
    lines = open(md_path, "r", encoding="utf-8").read().splitlines()
    items = []
    for ln in lines:
        m = re.match(r"- \[ \] (\d{4}-\d{2}-\d{2}) .*Pages? (\d+)\u2013?(\d+)", ln)
        if m:
            date, start, end = m.groups()
            items.append((date, int(start), int(end)))
    return items


TEMPLATE_PAGE = """
<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Page {page} — {pdf_name}</title>
  <style>
    :root{--header-h:64px; --nav-h:48px}
    html,body{height:100%;}
    body{display:flex; flex-direction:column; height:100vh; font-family:system-ui, -apple-system, "Segoe UI", Roboto, "Hiragino Kaku Gothic ProN", "Noto Sans JP", sans-serif; margin:0;}
    header{padding:12px; background:#222; color:#fff; flex:0 0 auto}
    /* two-column layout: left for PDF only, right stacked panes for Original / Translation */
    .nav{flex:0 0 auto; padding:12px; display:flex; gap:8px}
    .container{flex:1 1 auto; display:grid; grid-template-columns:45% 55%; gap:12px; padding:12px; min-height:0; overflow:hidden}
    .left-col{display:flex; flex-direction:column; gap:8px; min-width:0; min-height:0}
    .left-col h3{margin:0}
    .pdfbox{width:100%; border:0; height:100%; min-height:0}
    .right-col{display:flex; flex-direction:column; gap:12px; min-width:0; min-height:0}
    .pane{background:#fff; padding:8px; border-radius:6px; box-shadow:0 0 0 1px #eee inset; overflow:hidden; display:flex; flex-direction:column}
    .pane-header{margin:0 0 8px 0; display:flex; align-items:center; justify-content:space-between}
    .pane-content{white-space:pre-wrap; word-wrap:break-word; padding:8px; overflow:auto; flex:1;}
    /* Make each right pane share available height and scroll internally */
    .pane.half{flex:1; min-height:0}
    .nav{padding:12px; display:flex; gap:8px}
    .btn{padding:8px 12px; background:#0b63d6; color:#fff; border-radius:6px; text-decoration:none}
    .muted{color:#666}
    .playrow{display:flex; gap:8px; align-items:center}
  </style>
</head>
<body>
<header>
  <div style="display:flex;align-items:center;justify-content:space-between">
    <div><strong>{pdf_name}</strong> — Page {page}</div>
    <div class="muted">Generated by BookStand</div>
  </div>
</header>
  <div class="nav">
  <a class="btn" href="../index.html">Plan</a>
  {prev_link}
  {next_link}
  <div style="margin-left:auto">TTS rate: <select id="rate"><option>1.0</option><option>1.5</option><option>2.0</option></select></div>
</div>

<div class="container">
  <div class="left-col">
    <h3>PDF (embedded)</h3>
    <iframe class="pdfbox" src="{pdf_rel}#page={page}" title="PDF page {page}"></iframe>
  </div>
  <div class="right-col">
    <div class="pane half">
      <div class="pane-header">
        <h3 style="margin:0">Original (English)</h3>
        <div class="playrow">
          <button onclick="playText('{orig_js}', 'en-US')">▶ Play</button>
          <button onclick="pauseTTS()">⏸ Pause</button>
          <button onclick="resumeTTS()">▶ Resume</button>
          <button onclick="stopTTS()">⏹ Stop</button>
        </div>
      </div>
      <div class="pane-content">{orig_html}</div>
    </div>
    <div class="pane half">
      <div class="pane-header">
        <h3 style="margin:0">Japanese Translation</h3>
        <div class="playrow">
          <button onclick="playText('{trans_js}', 'ja-JP')">▶ Play</button>
          <button onclick="pauseTTS()">⏸ Pause</button>
          <button onclick="resumeTTS()">▶ Resume</button>
          <button onclick="stopTTS()">⏹ Stop</button>
        </div>
      </div>
      <div class="pane-content">{trans_html}</div>
    </div>
  </div>
</div>
<script>
  function escapeHTML(s){
    if(!s) return '';
    return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }
  let currentUtterance = null;
  function playText(text, lang){
    try{
      stopTTS();
      const utter = new SpeechSynthesisUtterance(text);
      utter.lang = lang;
      utter.rate = parseFloat(document.getElementById('rate').value||'1.0');
      currentUtterance = utter;
      speechSynthesis.speak(utter);
    }catch(e){
      alert('TTS not available in this browser')
    }
  }
  function pauseTTS(){
    try{ if(speechSynthesis.speaking && !speechSynthesis.paused) speechSynthesis.pause(); }catch(e){}
  }
  function resumeTTS(){
    try{ if(speechSynthesis.paused) speechSynthesis.resume(); }catch(e){}
  }
  function stopTTS(){
    try{ speechSynthesis.cancel(); currentUtterance = null; }catch(e){}
  }
</script>
</body>
</html>
"""



TEMPLATE_INDEX = """
<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Reading Plan — {pdf_name}</title>
<style>body{{font-family:system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; padding:18px}} a{{text-decoration:none}} .item{{padding:8px;border-bottom:1px solid #eee}}</style>
</head><body>
<h1>Reading Plan — {pdf_name}</h1>
<p>{plan_summary}</p>
<div>
{links}
</div>
</body></html>
"""


def make_safe_js(s):
  if not s:
    return ""
  # Escape backslash, single quote and newlines for safe inclusion in single-quoted JS string
  return s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "")


def generate(pdf_path, translations_md, plan_md, out_dir="html_output"):
  # Create directory structure: root/index.html, pages/, md/
  os.makedirs(out_dir, exist_ok=True)
  pages_dir = os.path.join(out_dir, 'pages')
  os.makedirs(pages_dir, exist_ok=True)
  reader = PdfReader(pdf_path)
  pdf_name = os.path.basename(pdf_path)
  trans = parse_translations(translations_md)
  plan = parse_plan(plan_md)

  total_pages = len(reader.pages)
  links_html = []
  for page in range(1, total_pages + 1):
    page_text = reader.pages[page - 1].extract_text() or ""
    trans_text = trans.get(page, "")
    # reflow English original into paragraph blocks, then escape
    orig_reflowed = reflow_paragraphs(page_text)
    orig_html = (orig_reflowed[:100000]).replace('<', '&lt;').replace('>', '&gt;')
    trans_html = (trans_text[:100000]).replace('<','&lt;').replace('>','&gt;')

    prev_link = f'<a class="btn" href="page{page-1}.html">◀ Prev</a>' if page>1 else ''
    next_link = f'<a class="btn" href="page{page+1}.html">Next ▶</a>' if page<total_pages else ''

    # Use safe replace to avoid interpreting other '{...}' in template CSS/JS
    page_html = TEMPLATE_PAGE
    page_html = page_html.replace('{page}', str(page))
    page_html = page_html.replace('{pdf_name}', pdf_name)
    # pages are in 'pages/' and PDF copy is in out_dir root, so use ../<pdf_name>
    page_html = page_html.replace('{pdf_rel}', os.path.join('..', pdf_name))
    page_html = page_html.replace('{prev_link}', prev_link)
    page_html = page_html.replace('{next_link}', next_link)
    page_html = page_html.replace('{orig_html}', orig_html)
    page_html = page_html.replace('{trans_html}', trans_html)
    page_html = page_html.replace('{orig_js}', make_safe_js(page_text[:6000]))
    page_html = page_html.replace('{trans_js}', make_safe_js(trans_text[:6000]))
    with open(os.path.join(pages_dir, f'page{page}.html'), 'w', encoding='utf-8') as f:
      f.write(page_html)
    links_html.append(f'<div class="item"><a href="pages/page{page}.html">Page {page}</a></div>')

  plan_summary = f'Total pages: {total_pages}'
  index_html = TEMPLATE_INDEX.format(pdf_name=pdf_name, plan_summary=plan_summary, links='\n'.join(links_html))
  with open(os.path.join(out_dir, 'index.html'), 'w', encoding='utf-8') as f:
    f.write(index_html)

  print(f'HTML pages generated to {out_dir}/ (index.html + pages/pageN.html)')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Export per-page HTML viewer for PDF + translations')
    parser.add_argument('pdf', help='Path to PDF file')
    parser.add_argument('--translations', default='translations.md', help='Path to translations.md')
    parser.add_argument('--plan', default='reading_plan.md', help='Path to reading_plan.md')
    parser.add_argument('--out', default='html_output', help='Output directory')
    args = parser.parse_args()
    generate(args.pdf, args.translations, args.plan, args.out)
